=== revenant/ipv6suite/Etc/netconf3.dtd
<?xml encoding="ISO-8859-1"?>
<!-- $Header: /home/cvs/IPv6Suite/IPv6SuiteWithINET/Etc/netconf3.dtd,v 1.2 2005/04/27 08:19:33 andras Exp $ -->

<!ELEMENT netconf (global?, local*, misc*)>
<!ATTLIST netconf 
          version NMTOKEN "0.0.6"
          debugChannel NMTOKEN #IMPLIED
          >

<!ELEMENT global EMPTY>

<!ELEMENT local (interface*, (route?| tunnel?| sourceRoute?|mobileConfig?)*)>
<!ATTLIST local 
          node NMTOKEN #REQUIRED
          routePackets (on|off) "off"
          forwardSitePackets (on|off) "on"
          mobileIPv6Support (on|off) "off"
          mobileIPv6Role (None|HomeAgent|MobileNode) "None"
          routeOptimisation (on|off) "on"
          respondBindingRequest (on|off) "off"       
          hierarchicalMIPv6Support (on|off) "off"
          map (on|off) "off"
          mapMode (Basic|Extended) "Basic"
          mapMNMAYSetRoCAAsSource (on|off) "on"
          mapMNMUSTSetRoCAAsSource (on|off) "on"
          mapReverseTunnel (on|off) "off"
          >

<!ELEMENT route (routeEntry)+>
<!ELEMENT routeEntry EMPTY>
<!ATTLIST routeEntry 
          routeIface NMTOKEN #REQUIRED
          routeDestination CDATA #REQUIRED
          routeNextHop CDATA ""
          isRouter (on|off) "off"
          >

<!ELEMENT sourceRoute (sourceRouteEntry)+>
<!ELEMENT sourceRouteEntry (nextHop)+>
<!ATTLIST sourceRouteEntry finalDestination CDATA #REQUIRED>
<!ELEMENT nextHop EMPTY>
<!ATTLIST nextHop address CDATA #REQUIRED>

<!ELEMENT tunnel (tunnelEntry)+>
<!ELEMENT tunnelEntry  (triggers)*>
<!ATTLIST tunnelEntry 
          exitIface NMTOKEN #REQUIRED
          entryPoint CDATA #REQUIRED
          exitPoint  CDATA #REQUIRED
          >
<!ELEMENT triggers EMPTY>
<!ATTLIST triggers destination CDATA #REQUIRED>

<!ELEMENT mobileConfig (homeAgent|mobileNode)>
<!ELEMENT homeAgent EMPTY>
<!ELEMENT mobileNode (staticConfig?)>

<!-- Used when mobile node is away from home during node startup -->
<!-- homeAgentAddr is the home agent's globally routable address with prefix specified. The home address is formed from this prefix on homeAddrIface. This can simply be the home prefix if the bits after prefix are 0 for testing of DHAAD -->
<!-- homeAddrIface references one of the interface elements of this local node by its name on this interface that has a route path to the home agent and will be where the home address is actually bound to -->

<!ELEMENT staticConfig EMPTY>
<!ATTLIST staticConfig  
          homeAddrIface NMTOKEN #REQUIRED
          homeAgentAddr CDATA #REQUIRED         
          >

<!ELEMENT interface (inet_addr*, AdvPrefixList?, AdvMAPList?, WirelessEtherInfo?)>

<!-- Require non ID type for name attribute as that requires each "interface
name" to be unique across whole xml document not just inside interface
element. -->
<!-- Use of MIPv6MaxRtrAdvInterval and MIPv6MinRtrAdvInterval when mobileIPv6Support is on -->
<!-- minRtrSolInterval is the relaxed Neighbour Discovery rtr solicitation interval-->
<!-- maxInterval is the maximum interval at which no further rtr sol attempts are made -->
<!ATTLIST interface 
          name NMTOKEN #IMPLIED
          AdvSendAdvertisements (on|off) "off"
          AdvHomeAgent (on|off) "off"
          MaxRtrAdvInterval NMTOKEN "600"
          MinRtrAdvInterval NMTOKEN "198"
          MIPv6MaxRtrAdvInterval NMTOKEN "1.5"
          MIPv6MinRtrAdvInterval NMTOKEN "0.05"
          MIPv6MinRtrSolInterval NMTOKEN "1"
          MIPv6MaxInterval NMTOKEN "8"
          > 

<!-- Suggested additions to phase out elements (non conformant default values)
UNPARSED -->
<!ATTLIST interface
          AdvManagedFlag (on|off) "off"
          AdvOtherConfigFlag (on|off) "off"
          AdvLinkMTU NMTOKEN "16000"
          AdvReachableTime NMTOKEN "2"
          AdvRetransTimer NMTOKEN "6"
          AdvCurHopLimit NMTOKEN "32"
          AdvDefaultLifetime NMTOKEN "0xFFFFFF"
          HostLinkMTU NMTOKEN "16000"
          HostCurHopLimit NMTOKEN "32"
          HostBaseReachableTime NMTOKEN "40"
          HostRetransTimer NMTOKEN "120"
          HostDupAddrDetectTransmits NMTOKEN "2"
          HMIPAdvMAP (on|off) "off"
          HMIPForwardMAPOption (on|off) "off"
          >

<!ELEMENT inet_addr (#PCDATA)>
<!ELEMENT AdvPrefixList (AdvPrefix)+>
<!ELEMENT AdvPrefix (#PCDATA)>
<!ATTLIST AdvPrefix 
          AdvValidLifetime NMTOKEN "2592000"
          AdvOnLinkFlag (on|off) "off"
          AdvPreferredLifetime NMTOKEN "605800"
          AdvAutonomousFlag (on|off) "on"
          AdvRtrAddrFlag (on|off) "off"
          >

<!ELEMENT AdvMAPList (AdvMAPEntry)+>
<!ELEMENT AdvMAPEntry (#PCDATA)>
<!ATTLIST AdvMAPEntry
          AdvMAPDist NMTOKEN "1"
          AdvMAPPref NMTOKEN "1"
          AdvMAPValidLifetime NMTOKEN "2592"
          >

<!-- Attributes of Wireless Ethernet (802.11) -->

<!ELEMENT WirelessEtherInfo (WEInfo, WESupportedRates?)>
<!ELEMENT WEInfo (#PCDATA)>
<!ATTLIST WEInfo
          WEssid NMTOKEN "default"
          WEPathLossExponent NMTOKEN "2.6"
          WEPathLossStdDev NMTOKEN "14.1"
          WETxPower NMTOKEN "100"
          WEThresholdPower NMTOKEN "-96"
          WEHOThresholdPower NMTOKEN "-90"
					WEProbeEnergyTimeout NMTOKEN "0.003"
					WEProbeResponseTimeout NMTOKEN "0.02"
          WEAuthenticationTimeout NMTOKEN "2"
          WEAssociationTimeout NMTOKEN "2"
          WERetry NMTOKEN "16">
<!ELEMENT WESupportedRates (WERate)+>
<!ELEMENT WERate (#PCDATA)>

<!-- Misc. options. Any conditions preset for the behaviour -->
<!-- the entire network. and they are part of IP configuration -->

<!ELEMENT misc (ObjectMovement*)>

<!ELEMENT ObjectMovement (MovingNode*)>
<!ATTLIST MovingNode 
          NodeName NMTOKEN #REQUIRED
          startTime NMTOKEN #REQUIRED
          >

<!ELEMENT MovingNode (move*)>
<!ELEMENT move EMPTY>
<!ATTLIST move 
          moveToX NMTOKEN #REQUIRED
          moveToY NMTOKEN #REQUIRED
          moveSpeed NMTOKEN #REQUIRED
          >

=== revenant/ipv6suite/Research/Networks/Baseline/Baseline.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE netconf SYSTEM "../../../Etc/netconf3.dtd">

<netconf debugChannel="debug.log:rcfile:MobileMove:notice">
  <local node="mn">
    <interface name="wlan0" HostDupAddrDetectTransmits="1" HostMaxRtrSolDelay="0">
    </interface>
  </local>
  <local node="cn">
    <interface name="eth0">
    </interface>
  </local>
   <misc>
        <ObjectMovement>
       <MovingNode NodeName="mn" startTime="0">
               <move moveToX="350" moveToY="70" moveSpeed="3"/>
       </MovingNode>
 </ObjectMovement>
  </misc>
</netconf>
